#!/usr/bin/env node
// Builds apps-script/Marketing.gs, the one file pasted into the Apps Script editor:
// the calendar core + the engine + the store, so the page and the store can never
// run different rules. `node tools/build-gs.js --check` fails if the built file is stale.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'apps-script', 'Marketing.gs');
const PARTS = ['marketing/calcore.js', 'marketing/engine.js', 'apps-script/Marketing.src.gs'];

function build(){
  const head = [
    '// GENERATED by tools/build-gs.js. Do not edit this file.',
    '// Edit marketing/calcore.js, marketing/engine.js or apps-script/Marketing.src.gs, then run: node tools/build-gs.js',
    '// Paste the whole file into the Apps Script editor of the Command Center Marketing Sheet (see apps-script/README.md).',
    ''
  ].join('\n');
  return head + PARTS.map(p => '\n// ---- ' + p + ' ' + '-'.repeat(Math.max(4, 70 - p.length)) + '\n' + fs.readFileSync(path.join(ROOT, p), 'utf8').trimEnd() + '\n').join('');
}

if (require.main === module) {
  const out = build();
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (cur !== out) { console.error('apps-script/Marketing.gs is stale. Run: node tools/build-gs.js'); process.exit(1); }
    console.log('apps-script/Marketing.gs is current.');
  } else {
    fs.writeFileSync(OUT, out);
    console.log('Wrote apps-script/Marketing.gs (' + out.length + ' chars).');
  }
}
module.exports = { build, OUT };
